// <auto-generated />
using System;
using LanguageLearning.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LanguageLearning.Common.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260806073413_AddExerciseEngineV2")]
    partial class AddExerciseEngineV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LanguageLearning.Common.Entities.ExerciseEngine.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercises_DisplayOrder", "\"DisplayOrder\" > 0");

                            t.HasCheckConstraint("CK_exercises_Version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.ExerciseEngine.ExerciseAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("EvaluationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("NotEvaluated");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExerciseVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Feedback")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("LessonAttemptExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LessonAttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("LessonAttemptExerciseId");

                    b.HasIndex("LessonAttemptId", "SubmissionId")
                        .IsUnique();

                    b.HasIndex("LessonAttemptId", "ExerciseId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("exercise_attempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercise_attempts_AttemptNumber", "\"AttemptNumber\" > 0");

                            t.HasCheckConstraint("CK_exercise_attempts_ExerciseVersion", "\"ExerciseVersion\" >= 1");

                            t.HasCheckConstraint("CK_exercise_attempts_Score", "\"Score\" IS NULL OR (\"Score\" >= 0 AND \"Score\" <= 100)");
                        });
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.ExerciseEngine.LessonAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CurrentActivityId")
                        .HasColumnType("uuid");

                    b.Property<int>("IncorrectCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("InProgress");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentActivityId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("lesson_attempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_lesson_attempts_Counts", "\"CorrectCount\" >= 0 AND \"IncorrectCount\" >= 0");

                            t.HasCheckConstraint("CK_lesson_attempts_TotalScore", "\"TotalScore\" >= 0 AND \"TotalScore\" <= 100");
                        });
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.ExerciseEngine.LessonAttemptExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExerciseVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonAttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceLessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserExerciseMistakeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("SourceLessonId");

                    b.HasIndex("UserExerciseMistakeId");

                    b.HasIndex("LessonAttemptId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("lesson_attempt_exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_lesson_attempt_exercises_DisplayOrder", "\"DisplayOrder\" > 0");

                            t.HasCheckConstraint("CK_lesson_attempt_exercises_ExerciseVersion", "\"ExerciseVersion\" >= 1");
                        });
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.ExerciseEngine.UserExerciseMistake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExerciseVersion")
                        .HasColumnType("integer");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstFailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastFailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("SuccessfulReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId", "ExerciseId")
                        .IsUnique();

                    b.HasIndex("UserId", "Status", "LastFailedAt");

                    b.ToTable("user_exercise_mistakes", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_exercise_mistakes_Counts", "\"FailureCount\" > 0 AND \"SuccessfulReviewCount\" >= 0");

                            t.HasCheckConstraint("CK_user_exercise_mistakes_ExerciseVersion", "\"ExerciseVersion\" >= 1");
                        });
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("User");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.Identity.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyGoalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NativeLanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user_profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_profiles_DailyGoalMinutes", "\"DailyGoalMinutes\" >= 5 AND \"DailyGoalMinutes\" <= 180");
                        });
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CefrLevel")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsPublished", "DisplayOrder");

                    b.ToTable("courses", null, t =>
                        {
                            t.HasCheckConstraint("CK_courses_DisplayOrder", "\"DisplayOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.LearningStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("InstructionText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("InstructionTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VocabularyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyId");

                    b.HasIndex("LessonId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("learning_steps", null, t =>
                        {
                            t.HasCheckConstraint("CK_learning_steps_DisplayOrder", "\"DisplayOrder\" > 0");
                        });
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("LearningObjectiveSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UnitId", "Code")
                        .IsUnique();

                    b.HasIndex("UnitId", "DisplayOrder")
                        .IsUnique();

                    b.HasIndex("UnitId", "Status", "DisplayOrder");

                    b.ToTable("lessons", null, t =>
                        {
                            t.HasCheckConstraint("CK_lessons_DisplayOrder", "\"DisplayOrder\" > 0");

                            t.HasCheckConstraint("CK_lessons_EstimatedDurationMinutes", "\"EstimatedDurationMinutes\" > 0");
                        });
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.LessonSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("lesson_sections", null, t =>
                        {
                            t.HasCheckConstraint("CK_lesson_sections_DisplayOrder", "\"DisplayOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsCaseSensitive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LearningStepId")
                        .HasColumnType("uuid");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PromptAudioUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("PromptImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("TargetVocabularyId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextAnswer")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearningStepId")
                        .IsUnique();

                    b.HasIndex("TargetVocabularyId");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessibilityText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("question_options", null, t =>
                        {
                            t.HasCheckConstraint("CK_question_options_DisplayOrder", "\"DisplayOrder\" > 0");
                        });
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Code")
                        .IsUnique();

                    b.HasIndex("CourseId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("units", null, t =>
                        {
                            t.HasCheckConstraint("CK_units_DisplayOrder", "\"DisplayOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.Vocabulary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ExampleSentence")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExampleTranslation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phonetic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyLevel");

                    b.HasIndex("Word");

                    b.ToTable("vocabularies", (string)null);
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.ExerciseEngine.Exercise", b =>
                {
                    b.HasOne("LanguageLearning.Common.Entities.LearningCatalog.Lesson", "Lesson")
                        .WithMany("Exercises")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.ExerciseEngine.ExerciseAttempt", b =>
                {
                    b.HasOne("LanguageLearning.Common.Entities.ExerciseEngine.Exercise", "Exercise")
                        .WithMany("ExerciseAttempts")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Common.Entities.ExerciseEngine.LessonAttemptExercise", "LessonAttemptExercise")
                        .WithMany("ExerciseAttempts")
                        .HasForeignKey("LessonAttemptExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Common.Entities.ExerciseEngine.LessonAttempt", "LessonAttempt")
                        .WithMany("ExerciseAttempts")
                        .HasForeignKey("LessonAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("LessonAttempt");

                    b.Navigation("LessonAttemptExercise");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.ExerciseEngine.LessonAttempt", b =>
                {
                    b.HasOne("LanguageLearning.Common.Entities.ExerciseEngine.LessonAttemptExercise", "CurrentActivity")
                        .WithMany()
                        .HasForeignKey("CurrentActivityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LanguageLearning.Common.Entities.LearningCatalog.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Common.Entities.Identity.User", "User")
                        .WithMany("LessonAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentActivity");

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.ExerciseEngine.LessonAttemptExercise", b =>
                {
                    b.HasOne("LanguageLearning.Common.Entities.ExerciseEngine.Exercise", "Exercise")
                        .WithMany("LessonAttemptExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Common.Entities.ExerciseEngine.LessonAttempt", "LessonAttempt")
                        .WithMany("Activities")
                        .HasForeignKey("LessonAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Common.Entities.LearningCatalog.Lesson", "SourceLesson")
                        .WithMany()
                        .HasForeignKey("SourceLessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Common.Entities.ExerciseEngine.UserExerciseMistake", "UserExerciseMistake")
                        .WithMany("ReviewActivities")
                        .HasForeignKey("UserExerciseMistakeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Exercise");

                    b.Navigation("LessonAttempt");

                    b.Navigation("SourceLesson");

                    b.Navigation("UserExerciseMistake");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.ExerciseEngine.UserExerciseMistake", b =>
                {
                    b.HasOne("LanguageLearning.Common.Entities.ExerciseEngine.Exercise", "Exercise")
                        .WithMany("UserExerciseMistakes")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Common.Entities.Identity.User", "User")
                        .WithMany("ExerciseMistakes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("LanguageLearning.Common.Entities.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.Identity.UserProfile", b =>
                {
                    b.HasOne("LanguageLearning.Common.Entities.Identity.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("LanguageLearning.Common.Entities.Identity.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.LearningStep", b =>
                {
                    b.HasOne("LanguageLearning.Common.Entities.LearningCatalog.Lesson", "Lesson")
                        .WithMany("LearningSteps")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Common.Entities.LearningCatalog.Vocabulary", "Vocabulary")
                        .WithMany()
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lesson");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.Lesson", b =>
                {
                    b.HasOne("LanguageLearning.Common.Entities.LearningCatalog.Unit", "Unit")
                        .WithMany("Lessons")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.LessonSection", b =>
                {
                    b.HasOne("LanguageLearning.Common.Entities.LearningCatalog.Lesson", "Lesson")
                        .WithMany("LessonSections")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.Question", b =>
                {
                    b.HasOne("LanguageLearning.Common.Entities.LearningCatalog.LearningStep", "LearningStep")
                        .WithOne("Question")
                        .HasForeignKey("LanguageLearning.Common.Entities.LearningCatalog.Question", "LearningStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageLearning.Common.Entities.LearningCatalog.Vocabulary", "TargetVocabulary")
                        .WithMany()
                        .HasForeignKey("TargetVocabularyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LearningStep");

                    b.Navigation("TargetVocabulary");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.QuestionOption", b =>
                {
                    b.HasOne("LanguageLearning.Common.Entities.LearningCatalog.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.Unit", b =>
                {
                    b.HasOne("LanguageLearning.Common.Entities.LearningCatalog.Course", "Course")
                        .WithMany("Units")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.ExerciseEngine.Exercise", b =>
                {
                    b.Navigation("ExerciseAttempts");

                    b.Navigation("LessonAttemptExercises");

                    b.Navigation("UserExerciseMistakes");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.ExerciseEngine.LessonAttempt", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ExerciseAttempts");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.ExerciseEngine.LessonAttemptExercise", b =>
                {
                    b.Navigation("ExerciseAttempts");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.ExerciseEngine.UserExerciseMistake", b =>
                {
                    b.Navigation("ReviewActivities");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.Identity.User", b =>
                {
                    b.Navigation("ExerciseMistakes");

                    b.Navigation("LessonAttempts");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.Course", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.LearningStep", b =>
                {
                    b.Navigation("Question");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.Lesson", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("LearningSteps");

                    b.Navigation("LessonSections");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("LanguageLearning.Common.Entities.LearningCatalog.Unit", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
